import type { Product } from '../types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Gold Ring',
    price: 150,
    image: '',
    description: 'Elegant gold ring with diamonds',
    category: 'jewelry',
  },
  {
    id: '2',
    name: 'Silver Necklace',
    price: 120,
    image: '',
    description: 'Stylish silver necklace',
    category: 'jewelry',
  },
  {
    id: '3',
    name: 'Leather Wallet',
    price: 50,
    image: '',
    description: 'Premium leather wallet',
    category: 'accessories',
  },
  {
    id: '4',
    name: 'Diamond Earrings',
    price: 200,
    image: '',
    description: 'Sparkling diamond earrings',
    category: 'jewelry',
  },
  {
    id: '5',
    name: 'Sunglasses',
    price: 80,
    image: '',
    description: 'Fashion sunglasses with UV protection',
    category: 'accessories',
  },
  {
    id: '6',
    name: 'Platinum Bracelet',
    price: 180,
    image: '',
    description: 'Luxury platinum bracelet',
    category: 'jewelry',
  },
  {
    id: '7',
    name: 'Backpack',
    price: 60,
    image: '',
    description: 'Stylish travel backpack',
    category: 'accessories',
  },
  {
    id: '8',
    name: 'Pearl Necklace',
    price: 130,
    image: '',
    description: 'Classic pearl necklace',
    category: 'jewelry',
  },
  {
    id: '9',
    name: 'Watch',
    price: 250,
    image: '',
    description: 'Luxury wristwatch',
    category: 'accessories',
  },
  {
    id: '10',
    name: 'Gold Earrings',
    price: 170,
    image: '',
    description: 'Elegant gold earrings',
    category: 'jewelry',
  },
];
